# Generated by Django 4.2.1 on 2023-05-11 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_status_post_status'),
    ]

    operations = [
    ]
